import Head from 'next/head'
import { Typography } from '@mui/material';

import Form from "../Components/Form";

export default function Home() {

  return (
    <>
      <Head>
        <title>Email Automation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant='h4' gutterBottom>
          Email Outreach
        </Typography>

        <Form />
      </main>


    </>
  )
}
